name = "cf-workers-status-page-v2"
workers_dev = true
account_id = "245410ac1a2f0eaf665dee44b50a9af3"
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2021-07-23"

[triggers]
crons = ["* * * * *"]

[site]
bucket = "out"
entry-point = "./"
